Associations
mariegrace31/school_library pull request #3
Opened 2023-09-14 17:34 UTC by mariegrace31

In this branch, I :

- Created a class ```Classroom```,
- Created the ```has-many```/```belongs-to``` relationship between ```Classroom``` and ```Student```,
- Created a class ```Book``` and ```Rental```,
- Created the ```many-to-many```  relationship between Person and Book.

2023-09-14 19:02 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @mariegrace31👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitHub Flow correctly 👍🏽
✅ Linter checks passed✔️
✅ Created a class Classroom✔️
✅ Created the has-many/belongs-to relationship between Classroom and Student✔️
✅ Created a class Book✔️
✅ Created a class Rental✔️
✅ Created the many-to-many relationship between Person and Book using the intermediate class Rental✔️


## Required Changes ♻️

> - [ ] According to the project requirement, please make sure that in the Student class, when setting the classroom for a student it also adds it to the classrooms' students. Adhering to this requirement is essential for maintaining our focus on meeting the project's specifications and ensuring that we stay on track.👍
> 
> ![add](https://github.com/mariegrace31/school_library/assets/40009354/72fdf9f1-c6b5-472a-9d52-be8bc21029ab)

> - [ ] According to the project requirements, please ensure that in the Person class, you establish the "has-many" relationship with the Rental class by including getters and setters for the @rentals attribute, initializing @rentals, and adding a method for adding rentals, as these elements are currently missing in your Person class. Adhering to this requirement is essential for maintaining our focus on meeting the project's specifications and ensuring that we stay on track.👍
> 
> ![add1](https://github.com/mariegrace31/school_library/assets/40009354/91dc09bf-d763-44f4-8680-7f4f783617aa)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 19:02 UTC, Johnadibe commented on book.rb
> +  attr_reader :rentals
> - [OPTIONAL] Great job on the `Book` class implementation! I advise you simplify your code by using `attr_accessor` for `title`, `author`, and `rentals`. This will automatically generate getter and setter methods for these attributes, making your code more concise. To learn more about these shortcuts, you can refer to the lesson [here](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_principles_examples.md#useful-shortcuts-attr_reader-attr_writer-and-attr_accessor).
> 
> Keep up the good work!👍
>

2023-09-14 19:02 UTC, Johnadibe commented on rental.rb
> +  attr_reader :book, :person
> - [OPTIONAL] Great job on the `Rental` class implementation! I advise you to simplify your code by using `attr_accessor` for `date`, `book`, and `person`. This will automatically generate getter and setter methods for these attributes, making your code more concise. To learn more about these shortcuts, you can refer to the lesson [here](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_principles_examples.md#useful-shortcuts-attr_reader-attr_writer-and-attr_accessor).
> 
> Keep up the good work!👍
>

2023-09-15 08:45 UTC, danmainah requested changes
Hi @mariegrace31 , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Implemented the suggested change to ensure the book and rental classes are correctly configured.

 # Required Changes ♻️

- [ ] @mariegrace31 as previously requested kindly add a classroom method in the student class that ensures the 'belongs-to' side (a student belongs to a classroom) of the relationship between student and classroom eg 
 ``` 
 def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

- [ ] @mariegrace31 As the previous reviewer had noted your person class is missing the ``add_rental`` method that accomplishes the "has-many" relationship.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 09:43 UTC, DammyShittu approved these changes
Hi @mariegrace31,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 09:44 UTC, merged